[package]
name = "pjdfs_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3.3.0"
rand = "0.8.5"
thiserror = "1.0.31"
strum = { version = "0.24.0", features = ["derive"] }
strum_macros = "0.24.0"
anyhow = "1.0.57"
once_cell = "1.12.0"
paste = "1.0.7"
gumdrop = "0.8.1"
figment = { version = "0.10.6", features = ["toml"] }
serde = { version = "1.0.138", features = ["derive"] }
inventory = "0.3.0"

[dependencies.nix]
version = "0.24.1"
features = ["fs", "socket"]

[lib]
name = "pjdfs_tests"
path = "src/lib.rs"

[[bin]]
name = "pjdfs_runner"
path = "src/main.rs"
