[package]
name = "pjdfs_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3.3.0"
rand = "0.8.5"
thiserror = "1.0.31"
strum = { version = "0.24.0", features = ["derive"] }
strum_macros = "0.24.0"
anyhow = "1.0.57"

[dependencies.nix]
version = "0.24.1"
features = ["fs", "socket"]

[lib]
name = "pjdfs_tests"
path = "src/lib.rs"

[[bin]]
name = "pjdfs_runner"
path = "src/main.rs"
