[book]
authors = ["musikid"]
language = "en"
multilingual = false
src = "src"
title = "PJDFSTest"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
