[book]
authors = ["Sayafdine Said", "Alan Somers"]
language = "en"
multilingual = false
src = "src"
title = "PJDFSTest"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/saidsay-so/pjdfstest"

[build]
build-dir = "../build"
create-missing = false
use-default-preprocessors = true